//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary_SocialKeeper
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class igroup192_DbContext : DbContext
    {
        public igroup192_DbContext()
            : base("name=igroup192_DbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblFavoriteContact> tblFavoriteContacts { get; set; }
        public virtual DbSet<tblHobbie> tblHobbies { get; set; }
        public virtual DbSet<tblInvite> tblInvites { get; set; }
        public virtual DbSet<tblLoctation> tblLoctations { get; set; }
        public virtual DbSet<tblNewUser> tblNewUsers { get; set; }
        public virtual DbSet<tblPreferredTime> tblPreferredTimes { get; set; }
        public virtual DbSet<tblSuggestedHobbie> tblSuggestedHobbies { get; set; }
        public virtual DbSet<tblSuggestedMeeting> tblSuggestedMeetings { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblUserHobbie> tblUserHobbies { get; set; }
        public virtual DbSet<tblActualMeeting> tblActualMeetings { get; set; }
    }
}
