//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary_SocialKeeper
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class igroup192_prodEntities : DbContext
    {
        public igroup192_prodEntities()
            : base("name=igroup192_prodEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PossibleFavoriteContact> PossibleFavoriteContact { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblActualMeeting> tblActualMeeting { get; set; }
        public virtual DbSet<tblFavoriteContact> tblFavoriteContact { get; set; }
        public virtual DbSet<tblHobbie> tblHobbie { get; set; }
        public virtual DbSet<tblInvite> tblInvite { get; set; }
        public virtual DbSet<tblLoctation> tblLoctation { get; set; }
        public virtual DbSet<tblNewUser> tblNewUser { get; set; }
        public virtual DbSet<tblPreferredTime> tblPreferredTime { get; set; }
        public virtual DbSet<tblSuggestedHobbie> tblSuggestedHobbie { get; set; }
        public virtual DbSet<tblSuggestedMeeting> tblSuggestedMeeting { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
        public virtual DbSet<tblUserHobbie> tblUserHobbie { get; set; }
    }
}
