//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary_SocialKeeper
{
    using System;
    using System.Collections.Generic;
    
    public partial class PossibleFavoriteContact
    {
        public int hobbieNum { get; set; }
        public string phonenuminvite { get; set; }
        public string phonenuminvited { get; set; }
        public int id { get; set; }
    
        public virtual tblHobbie tblHobbie { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
