//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary_SocialKeeper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHobbie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHobbie()
        {
            this.tblFavoriteContacts = new HashSet<tblFavoriteContact>();
            this.tblActualMeetings = new HashSet<tblActualMeeting>();
            this.tblSuggestedHobbies = new HashSet<tblSuggestedHobbie>();
            this.tblUserHobbies = new HashSet<tblUserHobbie>();
            this.PossibleFavoriteContacts = new HashSet<PossibleFavoriteContact>();
            this.tblSuggestedMeetings = new HashSet<tblSuggestedMeeting>();
        }
    
        public int hobbieNum { get; set; }
        public string hobbieName { get; set; }
        public string imageuri { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFavoriteContact> tblFavoriteContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblActualMeeting> tblActualMeetings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSuggestedHobbie> tblSuggestedHobbies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserHobbie> tblUserHobbies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PossibleFavoriteContact> PossibleFavoriteContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSuggestedMeeting> tblSuggestedMeetings { get; set; }
    }
}
