//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary_SocialKeeper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHobbie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHobbie()
        {
            this.PossibleFavoriteContact = new HashSet<PossibleFavoriteContact>();
            this.tblActualMeeting = new HashSet<tblActualMeeting>();
            this.tblFavoriteContact = new HashSet<tblFavoriteContact>();
            this.tblSuggestedMeeting = new HashSet<tblSuggestedMeeting>();
            this.tblSuggestedHobbie = new HashSet<tblSuggestedHobbie>();
            this.tblUserHobbie = new HashSet<tblUserHobbie>();
        }
    
        public int hobbieNum { get; set; }
        public string hobbieName { get; set; }
        public string imageuri { get; set; }
        public Nullable<float> Minhours { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PossibleFavoriteContact> PossibleFavoriteContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblActualMeeting> tblActualMeeting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFavoriteContact> tblFavoriteContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSuggestedMeeting> tblSuggestedMeeting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSuggestedHobbie> tblSuggestedHobbie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserHobbie> tblUserHobbie { get; set; }
    }
}
