//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary_SocialKeeper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvite
    {
        public string phoneNum1 { get; set; }
        public string phoneNum2 { get; set; }
        public string status { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblNewUser tblNewUser { get; set; }
    }
}
