//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary_SocialKeeper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoctation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLoctation()
        {
            this.tblSuggestedMeetings = new HashSet<tblSuggestedMeeting>();
            this.tblActualMeetings = new HashSet<tblActualMeeting>();
        }
    
        public int longitude { get; set; }
        public int latitude { get; set; }
        public string city { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSuggestedMeeting> tblSuggestedMeetings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblActualMeeting> tblActualMeetings { get; set; }
    }
}
