//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary_SocialKeeper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSuggestedMeeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSuggestedMeeting()
        {
            this.tblActualMeeting = new HashSet<tblActualMeeting>();
            this.tblSuggestedHobbie = new HashSet<tblSuggestedHobbie>();
        }
    
        public int meetingNum { get; set; }
        public System.TimeSpan startTime { get; set; }
        public System.TimeSpan endTime { get; set; }
        public string status { get; set; }
        public string phoneNum1 { get; set; }
        public string phoneNum2 { get; set; }
        public System.DateTime date { get; set; }
        public string rejectReason { get; set; }
        public double longitude { get; set; }
        public double latitude { get; set; }
        public Nullable<int> hobbieNum { get; set; }
        public Nullable<float> rank { get; set; }
        public Nullable<bool> isremindersend { get; set; }
        public Nullable<bool> isaskforranknotif { get; set; }
        public string event_id { get; set; }
        public string event_id_user2 { get; set; }
        public string event_id_defaultcal { get; set; }
        public string event_id_defaultcal_user2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblActualMeeting> tblActualMeeting { get; set; }
        public virtual tblHobbie tblHobbie { get; set; }
        public virtual tblLoctation tblLoctation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSuggestedHobbie> tblSuggestedHobbie { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
