//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary_SocialKeeper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSuggestedHobbie
    {
        public int meetingNum { get; set; }
        public int hobbieNum { get; set; }
        public bool isChosen { get; set; }
    
        public virtual tblHobbie tblHobbie { get; set; }
        public virtual tblSuggestedMeeting tblSuggestedMeeting { get; set; }
    }
}
