//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary_SocialKeeper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSuggestedMeeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSuggestedMeeting()
        {
            this.tblSuggestedHobbies = new HashSet<tblSuggestedHobbie>();
            this.tblActualMeetings = new HashSet<tblActualMeeting>();
        }
    
        public int meetingNum { get; set; }
        public System.TimeSpan startTime { get; set; }
        public System.TimeSpan endTime { get; set; }
        public string status { get; set; }
        public string phoneNum1 { get; set; }
        public string phoneNum2 { get; set; }
        public System.DateTime date { get; set; }
        public string rejectReason { get; set; }
        public int longitude { get; set; }
        public int latitude { get; set; }
    
        public virtual tblLoctation tblLoctation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSuggestedHobbie> tblSuggestedHobbies { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblActualMeeting> tblActualMeetings { get; set; }
    }
}
