//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary_SocialKeeper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.PossibleFavoriteContact = new HashSet<PossibleFavoriteContact>();
            this.PossibleFavoriteContact1 = new HashSet<PossibleFavoriteContact>();
            this.tblFavoriteContact = new HashSet<tblFavoriteContact>();
            this.tblFavoriteContact1 = new HashSet<tblFavoriteContact>();
            this.tblInvite = new HashSet<tblInvite>();
            this.tblPreferredTime = new HashSet<tblPreferredTime>();
            this.tblSuggestedMeeting = new HashSet<tblSuggestedMeeting>();
            this.tblSuggestedMeeting1 = new HashSet<tblSuggestedMeeting>();
            this.tblUserHobbie = new HashSet<tblUserHobbie>();
        }
    
        public string phoneNum1 { get; set; }
        public string userName { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string email { get; set; }
        public string city { get; set; }
        public string gender { get; set; }
        public string imageUri { get; set; }
        public Nullable<double> citylatt { get; set; }
        public Nullable<double> citylong { get; set; }
        public string ExpoPushToken { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PossibleFavoriteContact> PossibleFavoriteContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PossibleFavoriteContact> PossibleFavoriteContact1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFavoriteContact> tblFavoriteContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFavoriteContact> tblFavoriteContact1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInvite> tblInvite { get; set; }
        public virtual tblNewUser tblNewUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPreferredTime> tblPreferredTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSuggestedMeeting> tblSuggestedMeeting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSuggestedMeeting> tblSuggestedMeeting1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserHobbie> tblUserHobbie { get; set; }
    }
}
