//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary_SocialKeeper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.tblFavoriteContacts = new HashSet<tblFavoriteContact>();
            this.tblFavoriteContacts1 = new HashSet<tblFavoriteContact>();
            this.tblInvites = new HashSet<tblInvite>();
            this.tblPreferredTimes = new HashSet<tblPreferredTime>();
            this.tblSuggestedMeetings = new HashSet<tblSuggestedMeeting>();
            this.tblSuggestedMeetings1 = new HashSet<tblSuggestedMeeting>();
            this.tblUserHobbies = new HashSet<tblUserHobbie>();
            this.PossibleFavoriteContacts = new HashSet<PossibleFavoriteContact>();
            this.PossibleFavoriteContacts1 = new HashSet<PossibleFavoriteContact>();
        }
    
        public string phoneNum1 { get; set; }
        public string userName { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string email { get; set; }
        public string city { get; set; }
        public string gender { get; set; }
        public string imageUri { get; set; }
        public Nullable<double> citylatt { get; set; }
        public Nullable<double> citylong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFavoriteContact> tblFavoriteContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFavoriteContact> tblFavoriteContacts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInvite> tblInvites { get; set; }
        public virtual tblNewUser tblNewUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPreferredTime> tblPreferredTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSuggestedMeeting> tblSuggestedMeetings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSuggestedMeeting> tblSuggestedMeetings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserHobbie> tblUserHobbies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PossibleFavoriteContact> PossibleFavoriteContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PossibleFavoriteContact> PossibleFavoriteContacts1 { get; set; }
    }
}
